# Generated by Django 4.1.1 on 2022-09-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_worker',
            name='userid',
            field=models.CharField(default='nitwxyz123', max_length=10),
        ),
    ]
